name: CI/CD for Hosting Iris HTML App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependancies
      run: |
       python -m venv venv
       source venv/bin/activate
       pip install -r requirements.txt

    - name: Train the Model
      run: |
       source venv/bin/activate
       python train_model.py

    - name: Generate HTML app
      run: |
       source venv/bin/activate
       python generate_html.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./